FrontEndPersonalInfo/Models/ErrorViewModel.cs
namespace FrontEndPersonalInfo.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

FrontEndPersonalInfo/Models/InsertPersonalDetailsViewModel.cs
using System.ComponentModel;

namespace FrontEndPersonalInfo.Models
{
	public class InsertPersonalDetailsViewModel
	{
		[DisplayName("Name")]
		public string Name { get; set; }
		[DisplayName("Date of Birth")]
		public string DateOfBirth { get; set; }
		[DisplayName("Residential Address")]
		public string ResidentialAddress { get; set; }
		[DisplayName("Permanent Address")]
		public string PermanentAddress { get; set; }
		[DisplayName("Mobile Number")]
		public string MobileNumber { get; set; }
		[DisplayName("Email Address")]
		public string EmailAddress { get; set; }
		[DisplayName("Marital Status")]
		public string MaritalStatus { get; set; }
		[DisplayName("Gender")]
		public string Gender { get; set; }
		[DisplayName("Occupation")]
		public string Occupation { get; set; }
		[DisplayName("Aadhar Card Number")]
		public string AadharCardNumber { get; set; }
		[DisplayName("PAN Number")]
		public string PANNumber { get; set; }
		[DisplayName("Image (.jpg, .jpeg, .png)")]
		public IFormFile ImageFile { get; set; }
	}
}

FrontEndPersonalInfo/Models/PersonalInfoViewModel.cs
using System.ComponentModel;

namespace FrontEndPersonalInfo.Models
{
    public class PersonalInfoViewModel
    {
        public int Id { get; set; }
        [DisplayName("Person Name")]
        public string Name { get; set; }
        public string DateOfBirth { get; set; }
        public string ResidentialAddress { get; set; }
        public string PermanentAddress { get; set; }
        public string MobileNumber { get; set; }
        public string EmailAddress { get; set; }
        public string MaritalStatus { get; set; }
        public string Gender { get; set; }
        public string Occupation { get; set; }
        public string AadharCardNumber { get; set; }
        public string PANNumber { get; set; }
        public string ImageUrl { get; set; }
    }
}

FrontEndPersonalInfo/Controllers/HomeController.cs
using System.Diagnostics;
using FrontEndPersonalInfo.Models;
using Microsoft.AspNetCore.Mvc;

namespace FrontEndPersonalInfo.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

FrontEndPersonalInfo/Controllers/PersonalInfoController.cs
using FrontEndPersonalInfo.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace FrontEndPersonalInfo.Controllers
{
    public class PersonalInfoController : Controller
    {
        Uri baseAddress = new Uri("http://localhost:5120/api");
        private readonly HttpClient _client = new HttpClient();

        public PersonalInfoController()
        {


            _client = new HttpClient();
            _client.BaseAddress = baseAddress;
        }

        [HttpGet]
        public IActionResult Index()
        {
            List<PersonalInfoViewModel> personalInfolist = new List<PersonalInfoViewModel>();
            HttpResponseMessage response = _client.GetAsync(_client.BaseAddress + "/PersonalInfo").Result;
            if (response.IsSuccessStatusCode)
            {
                string data = response.Content.ReadAsStringAsync().Result;
                personalInfolist = JsonConvert.DeserializeObject<List<PersonalInfoViewModel>>(data);
            }


            return View(personalInfolist);
        }


        [HttpGet]
        public IActionResult AddDetails()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddDetails(InsertPersonalDetailsViewModel insertDetails)
        {
            if (ModelState.IsValid)
            {
                using (var details = new MultipartFormDataContent())
                {
                    // Add other fields
                    details.Add(new StringContent(insertDetails.Name), "Name");
                    details.Add(new StringContent(insertDetails.DateOfBirth), "DateOfBirth");
                    details.Add(new StringContent(insertDetails.ResidentialAddress), "ResidentialAddress");
                    details.Add(new StringContent(insertDetails.PermanentAddress), "PermanentAddress");
                    details.Add(new StringContent(insertDetails.MobileNumber), "MobileNumber");
                    details.Add(new StringContent(insertDetails.EmailAddress), "EmailAddress");
                    details.Add(new StringContent(insertDetails.MaritalStatus), "MaritalStatus");
                    details.Add(new StringContent(insertDetails.Gender), "Gender");
                    details.Add(new StringContent(insertDetails.Occupation), "Occupation");
                    details.Add(new StringContent(insertDetails.AadharCardNumber), "AadharCardNumber");
                    details.Add(new StringContent(insertDetails.PANNumber), "PANNumber");

                    // Add the file
                    if (insertDetails.ImageFile != null && insertDetails.ImageFile.Length > 0)
                    {
                        var fileContent = new StreamContent(insertDetails.ImageFile.OpenReadStream());
                        fileContent.Headers.ContentType = new System.Net.Http.Headers.MediaTypeHeaderValue(insertDetails.ImageFile.ContentType);
                        details.Add(fileContent, "ImageFile", insertDetails.ImageFile.FileName);
                    }

                    // Send to the API
                    var response = await _client.PostAsync($"{baseAddress}/PersonalInfo", details);

                    if (response.IsSuccessStatusCode)
                    {
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        ModelState.AddModelError(string.Empty, "An error occurred while uploading the details.");
                    }
                }
            }

            return View();
        }


        []
    }
}

FrontEndPersonalInfo/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

FrontEndPersonalInfo/Views/PersonalInfo/AddDetails.cshtml
@model FrontEndPersonalInfo.Models.InsertPersonalDetailsViewModel

@{
    ViewData["Title"] = "AddDetails";
}

<h1 class="text-center">Add Details</h1>
<hr />
<div class="row">
    <div class="col">
        <form asp-action="AddDetails" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateOfBirth" class="control-label"></label>
                <input asp-for="DateOfBirth" class="form-control" />
                <span asp-validation-for="DateOfBirth" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ResidentialAddress" class="control-label"></label>
                <input asp-for="ResidentialAddress" class="form-control" />
                <span asp-validation-for="ResidentialAddress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PermanentAddress" class="control-label"></label>
                <input asp-for="PermanentAddress" class="form-control" />
                <span asp-validation-for="PermanentAddress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MobileNumber" class="control-label"></label>
                <input asp-for="MobileNumber" class="form-control" />
                <span asp-validation-for="MobileNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EmailAddress" class="control-label"></label>
                <input asp-for="EmailAddress" class="form-control" />
                <span asp-validation-for="EmailAddress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MaritalStatus" class="control-label"></label>
                <input asp-for="MaritalStatus" class="form-control" />
                <span asp-validation-for="MaritalStatus" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Gender" class="control-label"></label>
                <input asp-for="Gender" class="form-control" />
                <span asp-validation-for="Gender" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Occupation" class="control-label"></label>
                <input asp-for="Occupation" class="form-control" />
                <span asp-validation-for="Occupation" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AadharCardNumber" class="control-label"></label>
                <input asp-for="AadharCardNumber" class="form-control" />
                <span asp-validation-for="AadharCardNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PANNumber" class="control-label"></label>
                <input asp-for="PANNumber" class="form-control" />
                <span asp-validation-for="PANNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageFile" class="control-label"></label>
                <input asp-for="ImageFile" class="form-control" />
                <span class="text-danger"></span>
            </div>
            <div class="d-flex justify-content-center">
                <div class="form-group m-3 text-center">
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
                <div class="form-group m-3 text-center">
                    <button type="button" value="Create" class="btn btn-secondary"> <a class="text-decoration-none text-white" asp-action="Index">Back to List</a> </button>                  
                </div>
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FrontEndPersonalInfo/Views/PersonalInfo/Index.cshtml
@model IEnumerable<FrontEndPersonalInfo.Models.PersonalInfoViewModel>

@{
    ViewData["Title"] = "Index";
}

<p class="text-center"> 
    <button class="btn btn-outline-success"><a class="text-decoration-none text-black " asp-action="adddetails">Create New User</a></button>
</p>

<div class="d-flex flex-lg-wrap justify-content-center">
    @foreach (var item in Model)
    {
        <div class="card m-3" style="width: 18rem;">
            <img src="@Url.Content(item.ImageUrl)" class="card-img-top" alt="...">
          <div class="card-body">
            <h5 class="card-title text-center border-bottom p-1">@Html.DisplayFor(modelItem => item.Name)</h5>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">@Html.DisplayFor(modelItem => item.EmailAddress)</li>
                    <li class="list-group-item">@Html.DisplayFor(modelItem => item.MobileNumber)</li>
                </ul>
            <a asp-action="personaldetials" class="btn btn-primary m-2">View More</a>
          </div>
        </div>
    }
</div>

FrontEndPersonalInfo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FrontEndPersonalInfo</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FrontEndPersonalInfo.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="PersonalInfo" asp-action="Index">User</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - FrontEndPersonalInfo - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>